server:
  port: 5088
  compression:
    enabled: true

spring:
  datasource:
    userdb:
      username: root
      password: mysql
      jdbc-url: jdbc:mysql://localhost:3306/user_db
      driver-class-name: com.mysql.cj.jdbc.Driver
    coursedb:
      username: root
      password: mysql
      jdbc-url: jdbc:mysql://localhost:3306/course_db
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/coursedb/*.xml, classpath:mybatis/userdb/*.xml
  type-aliases-package: com.shengkai.demo.entity.coursedb, com.shengkai.demo.entity.userdb
  configuration:
    map-underscore-to-camel-case: true